### ISSUE TITLE
Offline report generation

### ISSUE THREAD

**Issue by cenx1** [allure-framework/allure-cli#17]
Hi
I am investigating if we can use this tool in our development pipeline, and I stumbled upon the section specifying that the files used for generating reports are downloaded at generate-time. Are there any way to circumvent this behavior? 
The server running our builds, and thought of to implement your tool in, is not able to connect outside of our network. Can we host a copy of the files in our network and change something in a config-file?

Thanks in advance.

**Comment by pavelsusloparov** [comment]
Hi, any updates here? It will be great to have official version.

I did workaround, but it works not well(version 1.4.0RC5 gives front-end weird behaviour).
Or i forget something in shadow jar.

Created maven shadow pom.xml with all allure cli dependencies.
Generated allure cli jar file with all dependencies(mvn package)
Use execute bash command inside gradle task to generate report using new jar file.


```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><groupId>com.nytimes.allure</groupId><artifactId>allure-cli-shell</artifactId><version>1.15.x-DEV-SNAPSHOT</version><packaging>jar</packaging><name>ALLURE-CLI-SHELL</name><dependencies><dependency><groupId>ru.yandex.qatools.allure</groupId><artifactId>allure-cli</artifactId><version>1.4.0.RC5</version></dependency></dependencies><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-shade-plugin</artifactId><version>1.6</version><configuration><createDependencyReducedPom>true</createDependencyReducedPom><filters><filter><artifact>*:*</artifact><excludes><exclude>META-INF/*.SF</exclude><exclude>META-INF/*.DSA</exclude><exclude>META-INF/*.RSA</exclude></excludes></filter></filters></configuration><executions><execution><phase>package</phase><goals><goal>shade</goal></goals><configuration><transformers><transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/><transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer"><mainClass>ru.yandex.qatools.allure.AllureCli</mainClass></transformer></transformers></configuration></execution></executions></plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-jar-plugin</artifactId><version>2.3.2</version><configuration><archive><manifest><addDefaultImplementationEntries>true</addDefaultImplementationEntries></manifest></archive></configuration></plugin></plugins></build></project>
```

**Comment by baev** [comment]
New version of Allure command line client supports the offline mode. See http://wiki.qatools.ru/display/AL/Allure+CLI
