### ISSUE TITLE
Report With Invocation Error

### ISSUE THREAD

**Issue by mariohmol** [allure-framework/allure-cli#24]
I'm trying to generate the HTML Report from a XML, after running py.test, but i'm gettting a error.

I ran the xml files as:
* py.test exportacao\check\step_5_site.py --alluredir F:\Projetos\datavivaetl\dados\tests

When i try to run the generate:
* allure generate F:\Projetos\datavivaetl\dados\tests

I got this error: 
* java.lang.reflect.InvocationTargetException

And thats all..  shows in terminal just this line.. isnt a full log with stacktrace?

My env:
* Windows 7 64 Bits
* Python 64 Bits 2.7.7
* PyTest 2.6.4
* PyTest-allure-adaptor-1.5.1
* Allure version 2.1

I tryied using version 1.4.4 and 1.3.9, like above:
allure report generate F:\Projetos\datavivaetl\dados\tests -v 1.3.9

Same error!

What am i doing wrong?

**Comment by baev** [comment]
New version of Allure command line client supports the offline mode. See http://wiki.qatools.ru/display/AL/Allure+CLI
