### ISSUE TITLE
log4j errors while generating reports

### ISSUE THREAD

**Issue by alvassin** [allure-framework/allure-cli#26]
Using latest release build https://github.com/allure-framework/allure-cli/releases/tag/allure-cli-2.3

I see following errors when generating reports using `-v 1.4.2` arguments:
```
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [java.net.URLClassLoader@55aa7971] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@7d6bb63e].
log4j:ERROR Could not instantiate appender named "console"
```

**Comment by LeXuZZ** [comment]
when i'm use 1.4.8 version, i have error

log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "
org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [java.net.URLClassLoader@1a8622] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$
AppClassLoader@1f96302].
log4j:ERROR Could not instantiate appender named "console".
log4j:WARN No appenders could be found for logger (ru.yandex.qatools.allure.data.utils.ServiceLoaderUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by baev** [comment]
@alvassin @LeXuZZ it is not an errors, it is just log4j warnings. You can ignore it

BTW we fix it in next releases

**Comment by baev** [comment]
There is no more log4j errors in new command line client. See http://wiki.qatools.ru/display/AL/Allure+CLI
