### ISSUE TITLE
allure.tests.management.pattern is unsupported as CLI argument

### ISSUE THREAD

**Issue by echoAlexey** [allure-framework/allure-cli#29]
Hi, 

Currently allure.tests.management.pattern parameter is unsupported in CLI tool. 
It would be great to pass it in a same way as "version"...

**Comment by vania-pooh** [comment]
@echoAlexey how about passing -Dallure.tests.management.pattern=123 to command line?

**Comment by echoAlexey** [comment]
@vania-pooh yes, we do in a such way: java [-options] -jar ${ALLURE_CLI_JAR} $@
If passed after -jar then options go as command line args instead of system properties.

**Comment by baev** [comment]
New command line client has ability to provide *allure.properties*. See http://wiki.qatools.ru/display/AL/Allure+CLI#AllureCLI-Configuration
