### ISSUE TITLE
getting java.lang.nullpointer exception when running on windows

### ISSUE THREAD

**Issue by jainvarz** [allure-framework/allure-cli#35]
Hi

I have installed the nunit adapter (2.6.4) for allure and was able to generate xml files with allure adapter
However when i go ahead to create reports with allure cli I am always getting java.lang.nullpointer exception
Appreciate Any help on this

**Comment by vania-pooh** [comment]
@jainvarz any details about this exception would be appreciated. You could run CLI with --debug option to view more details.

**Comment by jainvarz** [comment]
Hello 
After running with debug
I am getting error like this

C:\allure-cli 2_3\bin>allure --debug generate c:\testResults\AllureResults
Generating report for Allure version [1.3.9]
Processing result pattern [c:\testResults\AllureResults]
Found results directory [c:\testResults\AllureResults]
Connection request: [route: {}->http://repo1.maven.org][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 100]
Connection leased: [id: 0][route: {}->http://repo1.maven.org][total kept alive:0; route allocated: 1 of 50; total allocated: 1 of 100]
Connecting to repo1.maven.org:80
Connection org.apache.http.impl.conn.DefaultClientConnection@31153228 closed
Connection org.apache.http.impl.conn.DefaultClientConnection@31153228 shut down
Connection org.apache.http.impl.conn.DefaultClientConnection@31153228 closed
Connection released: [id: 0][route: {}->http://repo1.maven.org][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 100]java.lang.NullPointerException ru.yandex.qatools.allure.report.AllureReportBuilderException:java.lang.NullPointerException

Looks like some issues with connecting to maven

**Comment by cryptton2004** [comment]
Hello,
I'm encountering the same issue.


allure.bat --debug generate path\build -v 1.4.0
Generating report for Allure version [1.4.0]
Processing result pattern [path\build]
Found results directory [path\build]
Connection request: [route: {}->http://repo1.maven.org][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 100]
Connection leased: [id: 0][route: {}->http://repo1.maven.org][total kept alive:
0; route allocated: 1 of 50; total allocated: 1 of 100]
Connecting to repo1.maven.org:80
Connection org.apache.http.impl.conn.DefaultClientConnection@16425a2 closed
Connection org.apache.http.impl.conn.DefaultClientConnection@16425a2 shut down
Connection org.apache.http.impl.conn.DefaultClientConnection@16425a2 closed
Connection released: [id: 0][route: {}->http://repo1.maven.org][total kept alive
: 0; route allocated: 0 of 50; total allocated: 0 of 100]
java.lang.NullPointerException ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.NullPointerException

Any thoughts?

**Comment by meesala9** [comment]
Any update on the issue. I can still replicate the issue and can't go any further.

Thanks in advance for the information.

**Comment by cryptton2004** [comment]
I managed to work around it by manually generating the build from the latest files.

**Comment by hchiao** [comment]
Hi cryptton2004,

Can you please give more details as to how you resolved the issue?  I am running the binary behind a proxy, I am suspecting that is the problem.  Currently trying to by pass this issue with information from this web page https://github.com/allure-framework/allure-report-builder/issues/3.  However, I don't seem to be able to get proxy settings working on maven.

Cheers,
MIke

**Comment by cryptton2004** [comment]
Hi,

I don't have much knowledge about java so I won't be able to point you on what you have to do when you encounter errors from the cli. However, I imported this project in eclipse and generated the binary. When executing the generation of the report, I used different versions until one worked (this currently works for me -v 1.4.0). Also, for generating the xml file I use phpunit library (since my tests are phpunit+selenium based). The following tags work for me without braking the report: title, description, features, step, story. Haven't tried others for a long time (I think 'issues' was kind of braking the format of the xml). I can share the executable if you wish, maybe it will work for you also. (http://www.fileshare.ro/e31830402)

Good luck,
Cristian

**Comment by cryptton2004** [comment]
also, you might need to download the dependencies to C:\users\USED_USER\.m2\repository\ru\yandex...

**Comment by baev** [comment]
this CLI was deprecated, use the new one http://wiki.qatools.ru/display/AL/Allure+CLI
