### ISSUE TITLE
Can't generate report under linux mint

### ISSUE THREAD

**Issue by alex-klimovich** [allure-framework/allure-cli#40]
I installed `allure-cli` by typing in console:

    $ sudo apt-add-repository ppa:yandex-qatools/allure-framework
    $ sudo apt-get update
    $ sudo apt-get install allure-cli

then I generated xml file using `allure-python`.
In tests directory I have folder `allure-results` with test results and when i run command

    $ allure generate allure-results/

it prints me 

    WARN: No current version specified. Use `allure switch <version>` to select version of the report.

Then I type

    $ allure switch 1.3.9

and it prints me 

    ERROR: Could not switch to version "1.3.9": the version is not installed.%nThe installed versions: [].

**Comment by alex-klimovich** [comment]
I have tested on version 2.3 and client version 2.3 works fine. Version 2.4 I think is bugged.

**Comment by baev** [comment]
version 2.4 can generate only versions 1.4.16 or higher

**Comment by alex-klimovich** [comment]
$ allure switch 1.4.16
    ERROR: Could not switch to version "1.4.16": the version is not installed.%nThe installed versions: [].

I do something wrong?

**Comment by baev** [comment]
try `allure updgrade` command

**Comment by alex-klimovich** [comment]
$ allure upgrade
    Downloading bundle with version 1.4.17 ...
    Switched to bundle 1.4.17.

    $ allure generate allure-results/
    Report successfully generated to the directory "allure-report". Use `allure report open` command to show the report.

Yea, it helps! Thanks!

**Comment by baev** [comment]
you are welcome.
