### ISSUE TITLE
Could not find any allure results

### ISSUE THREAD

**Issue by windwaker** [allure-framework/allure-cli#41]
* I installed allure-cli manually from zip file and ran 'allure upgrade'
* I then ran ./allure report generate '/root/xUnit_XML/' which contains my test results (generated by robot framework)
* This is the xml file: ```<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="0" tests="2" errors="0" name="Hw Indep Vcenter Tests" skip="0">
<testcase classname="Hw Indep Vcenter Tests" name="Test vCenter - Compute OS Details" time="1">
</testcase>
<testcase classname="Hw Indep Vcenter Tests" name="Test vCenter - Compute OS details via Component URI" time="1">
</testcase>
</testsuite>```
* I get the following error 
    ```[root@localhost bin]# ./allure report generate '/root/xUnit_XML/'
Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
ERROR: Command aborted due to exception org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1).```
* Is there a problem with my XML or my configuration?

**Comment by vania-pooh** [comment]
@windwaker please first of all check that your XML corresponds to the following schema: https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd
Summon @eroshenkoam

**Comment by windwaker** [comment]
Oh-Oh, looks like it has a 'testsuite' element instead of 'test-suite'

Cvc-elt.1: Cannot Find The Declaration Of Element 'test-suite'.. Line '1', Column '86'.

**Comment by vania-pooh** [comment]
@windwaker I can't find any Allure adapter for robot framework? Could you point me to repository where the adapter's source code resides?

**Comment by windwaker** [comment]
@vania-pooh no adapter exists to my knowledge, what I did was generate an xUnit compatible XML report (include  -x option on the command line) from Robot and use that as input to the allure CLI

**Comment by baev** [comment]
@windwaker Allure can't generate the report from xUnit XML

**Comment by windwaker** [comment]
@baev Thanks, I see now that allure works on a supplemented xUnit XMl file. I'm gonna look into adapting the output from Robot but for now, I'll close this defect. Thanks to everyone for their help.
